# Generated by Django 2.2.2 on 2019-08-17 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default=None, max_length=200)),
                ('destination_name', models.CharField(default=None, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('structure_type', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('building_material', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('service', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('construction_operation', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('specific_project_type', models.CharField(default=None, max_length=200)),
                ('project_description', models.CharField(default=None, max_length=500)),
                ('documentation_path', models.CharField(default=None, max_length=200)),
                ('project_manager', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
